apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-actions-hw
  labels:
    app: gh-actions-hw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gh-actions-hw
  template:
    metadata:
      labels:
        app: gh-actions-hw
    spec:
      containers:
      - name: gh-actions-hw
        image: katka05/gh-actions-hw:latest
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: gh-actions-hw-service
spec:
  type: NodePort
  selector:
    app: gh-actions-hw
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30090