name: build-test

on:
  push: 
  workflow_dispatch: 

jobs:
  clean:
    name: clean_build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean
  compile:
    name: compile-build
    runs-on: self-hosted
    needs: clean
    steps:
      - run: mvn compile
  package:
    name: package-build
    runs-on: self-hosted
    needs: compile
    steps:
      - run: mvn package
  test:
    name: test-runs
    runs-on: self-hosted
    needs: package
    steps:
      - run: mvn test