name: CI_Inbuild_Actions

on:
  push: 
  workflow_dispatch: 

jobs:
  clean:
    name: clean_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean

  compile:
    name: compile-build
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - uses: actions/checkout@v4
      - run: mvn compile

  package:
    name: package-build
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - run: mvn package
      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/hello-world-webapp-1.0.0.jar

  test:
    name: test-runs
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v4
      - run: mvn test

  image_build:
    name: docker-image-build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Built JAR
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: target  # Ensure it is placed in the correct directory

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/gh-actions-hw:v1
