name: CI_Inbuild_Actions

on:
  push: 
  workflow_dispatch: 

jobs:
  clean:
    name: clean_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean
  compile:
    name: compile-build
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - uses: actions/checkout@v4
      - run: mvn compile
  package:
    name: package-build
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - run: mvn package
  test:
    name: test-runs
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v4
      - run: mvn test
  image_build:
    name: docker-image-build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/gh-actions-hw:v1
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: image_build
  #   steps:
  #     - name: Set Kubernetes Context
  #       uses: azure/k8s-set-context@v3
  #       with:
  #         method: kubeconfig
  #         kubeconfig: ${{ secrets.KUBECONFIG }}
  #     - name: Cleanup Previous Depolyment
  #       run: kubectl delete -f k8s/deployment.yaml
  #     - name: Deploy Application
  #       run: kubectl apply -f k8s/deployment.yaml
          