name: build-test

on:

  workflow_dispatch: 

jobs:
  clean:
    name: clean_build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean
  build:
    name: build-package
    runs-on: self-hosted
    steps:
      - run: mvn package