name: build-test

on:
  push: 
  workflow_dispatch: 

jobs:
  clean:
    name: clean_build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean
  compile:
    name: compile-build
    runs-on: self-hosted
    needs: clean
    steps:
      - run: mvn compile
  package:
    name: package-build
    runs-on: self-hosted
    needs: compile
    steps:
      - run: mvn package
  test:
    name: test-runs
    runs-on: self-hosted
    needs: package
    steps:
      - run: mvn test
  image_build:
    name: docker-image-build
    runs-on: self-hosted
    needs: test
    steps:
      - name: Configure Docker to Ignore Credential Helper
        run: |
          mkdir -p ~/.docker
          echo '{ "credsStore": "" }' > ~/.docker/config.json
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u katka05 --password-stdin
      - name: Do image build
        run: docker build -t katka05/gh-actions-hw:latest .
      - name: Push to DockerHub
        run: docker push katka05/gh-actions-hw:latest
  deploy:
    runs-on: self-hosted
    needs: image_build
    steps:
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Cleanup Previous Depolyment
        run: kubectl apply -f k8s/deployment.yaml
      - name: Deploy Application
        run: kubectl apply -f k8s/deployment.yaml
          