name: GH_Actions

on: 
    push: 
    workflow_dispatch: 

jobs:
    build_steps:
        name: clean_build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                mvn clean
                mvn compile
                mvn package
                mvn test
            - name: Upload JAR as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: built-jar
                path: target/hello-world-webapp-1.0.0.jar

    image_build:
        name: docker-image-build
        runs-on: ubuntu-latest
        needs: build_steps
        steps:
            - uses: actions/checkout@v4
            
            - name: Download Built JAR
              uses: actions/download-artifact@v4
              with:
                name: built-jar
                path: .

            - name: List files for debugging (Check if JAR exists)
              run: ls -lah .

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/gh-actions-hw:v1
