name: GH_Actions

on: 
    push: 
    workflow_dispatch: 

jobs:
    image_build:
        name: docker-image-build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/gh-actions-hw:v1
