name: GH_Actions

on: 
    push: 
    workflow_dispatch: 

jobs:
    build_steps:
        name: clean_build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                mvn clean
                mvn compile
                mvn package
                mvn test
            - name: Upload JAR as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: built-jar
                path: target/hello-world-webapp-1.0.0.jar
            